#! /usr/bin/bash
# program on use case of integer companision

read -p 'Enter A value:' a_value
read -p 'Enter B value:' b_value

if [ $ a_value -gt $ b_value ]
then
     echo"The value of A is greater than B"
else
     echo "The value of B is greater than A"
fi

