#! /usr/bin/bash
# program on use case of integer companision

read -p 'enter a value:' a_value
read -p 'enter b value:' b_value

if [ $ a_value -gt $ b_value ]
then
     echo"the value of a is greater than b"
else
     echo "the value of b is greater than a"
fi

