-
  name: code for project
  hosts: client1
  tasks:

    - name: upadate package cache
      package:
        name: epel-release
        state: present

    - name: code to install apache
      package:
        name: httpd
        state: present

    - name: code to start services
      service:
        name: httpd
        enable: yes

    - name: code to create directory
      file:
        path: /opt/apache-logs
        state: directory

    - name: code to create a file
      file:
        path: /opt/apache-logs/apache-logs.logs
        state: touch

    - name: code to write a message into file
      copy:
        content: "Apache successfully installed"
        dest: /opt/apache-logs/apache-logs.logs

    - name: code to write html code in apache webserver
      copy:
        dest: /var/www/html/index.html
        content: "<html>
             <body>
             <h1> Ansible Project sample </h1>
             </body>
             </html>"

