-
  name: pb on use case of variable concept
  hosts: client1
  tasks:
    - name: below code for yum installation using loop
      yum:
        name: "{{ item }}"
        state: present
      with_items:
         - git
         - docker
         - net-tools
         - finger
