-
  name: pb to code to update the version
  hosts: client1
  tasks:
    - name: Ensure apache is at latest version
      yum:
        name: httpd
        state: present

    - name: Write the apache config file
      template:
        src: /srv/httpd.j2
        dest: /etc/httpd.conf

    - name: update the db server
      hosts: databases
      remote_user: root
      tasks:
        - name: ensure postgre sql is at the latest version
          yum: 
            name: postgre sql
            state: latest

        - name: ensure that postgre sql is started
          service:
            name: postgre sql
            state: started


